"2","Error: invoke_wrapped: throwing std::runtime_error
"
